### ISSUE TITLE
Inconsistent configuration file location

### ISSUE THREAD

**Issue by karlsson3** [streamlink/streamlink-portable#13]
I put the portable installation here C:/streamlink/
And the default configuration file is in there aswell: C:/streamlink/streamlinkrc
But when I want to specify settings for each plugin I have to put the streamlinkrc.twitch in %AppData%/streamlink/streamlinkrc.twitch otherwise it won't work.
The regular streamlinkrc configuration file won't work if it is with the rest of the plugin specific files in %AppData%/streamlink/

The plugin specific configuration files should be at the same place the streamlinkrc is.

And maybe you should add the information about the portable version here aswell: https://streamlink.github.io/cli.html#configuration-file
Took me some time to figure out why streamlink ignored my configuration in %appData%

**Comment by RosadinTV** [comment]
Thanks for the report, i will try to fix this soon.

**Comment by karlsson3** [comment]
You fixed it, thanks! Works great now!
