### ISSUE TITLE
--loglevel does not affect launch and exit text

### ISSUE THREAD

**Issue by CaneCraft** [streamlink/streamlink-portable#17]
Regardless of --loglevel level, typing in a command will _always_ display the following:

`[Streamlink for Windows v0.7.0 - Git b657864]`
`...`
`[End of Streamlink for Windows with ExitCode 0]`

This messes up the input box in the .bat file I'm using to launch various streams. Any way to get rid of it?

**Comment by RosadinTV** [comment]
@CaneCraft 
Should be fixed with https://github.com/streamlink/streamlink-portable/commit/edcbb2a870a010c0bc0be0162ffc5f35e1e45324
Create a file named 'NO_CMD_HINTS' inside Releases folder.

**Comment by CaneCraft** [comment]
Yep, works perfectly. Thanks Rosadin. =)
