### ISSUE TITLE
Portable version not running

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink-portable#18]
Hi,
I have download the zip folder from here: https://github.com/streamlink/streamlink-portable/releases

And I am running the exe file and it asks me to input : "Type a valid command"
I am a giving command : streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "C:\Users\name\Videos\ok.ts" https://www.youtube.com/watch?v=E1j6MMm_UuM 144p

But after that nothing happens and it says : [ Streamlink for windows v.0.7.0] 

I am using windows 7 64 bit machine. And a i am looking for a streamlink file in which I do not have to install the file and I can directly run streamlink.
Do I have to install VLC for this?

**Comment by CheesyWiggles** [comment]
You don't need the streamlink at the start. Just use
--hls-live-edge 99999 --hls-segment-threads 5 -o "C:\Users\name\Videos\ok.ts" https://www.youtube.com/watch?v=E1j6MMm_UuM 144p

**Comment by rusty148** [comment]
Thank you so much. It works.
But I can't open the files in Windows media player. Can you suggest me an extension to save? .mp4 does not work. also not avi, mkv, etc

**Comment by RosadinTV** [comment]
@rusty148 
I suggest you to use another player such as VLC, MPV or MPC-HC (https://streamlink.github.io/players.html#player-compatibility)
When you change the extension with -o parameter, the file format is not actually changed, to do that you need to use a program like ffmpeg or avconv.
