### ISSUE TITLE
Unicode issue when using streamlink portable in differentt app locale.

### ISSUE THREAD

**Issue by Dalonomus** [streamlink/streamlink-portable#20]
Ok this is a bit strange because i assumed Livestreamer was a Unicode program but anyway.  Ive been using portable because normal livestream seems to dislike me on windows 10.  Until i tried to solve another problem Ive been having which relates to a bunch of files I created with app locale set to Japanese.  Basically put when I have it set to United states English everything works as is.  But when I switch it to Japanese app locale the program gives me something about a unicode error in the command line interface.  Can i fix this??  Id like to leave my app locale as Japanese until I can solve this file problem.  And i know Streamlink in general works this way because the mainline worked just fine on my windows 7 machine with app locale set to japanese.  If you need it I can provide the exact message streamlink put out but that'll need a restart.

**Comment by RosadinTV** [comment]
Hi.
Yes, if you can send a screenshot (preferably) or the exact message would be great.

**Comment by Dalonomus** [comment]
[Streamlink for Windows v0.9.0 - Git f6708f1]
Traceback (most recent call last):
  File "I:\Music+soundtracks\Streamlink_for_Windows_Portable_v0.9.0\Streamlink\Streamlink.py", line 7, in <module>
    main()
  File "I:\Music+soundtracks\Streamlink_for_Windows_Portable_v0.9.0\Streamlink\streamlink_cli\main.py", line 1022, in main
    setup_config_args()
  File "I:\Music+soundtracks\Streamlink_for_Windows_Portable_v0.9.0\Streamlink\streamlink_cli\main.py", line 609, in setup_config_args
    setup_args(config_files)
  File "I:\Music+soundtracks\Streamlink_for_Windows_Portable_v0.9.0\Streamlink\streamlink_cli\main.py", line 581, in setup_args
    args = parser.parse_args(arglist)
  File "argparse.py", line 1726, in parse_args
  File "argparse.py", line 1758, in parse_known_args
  File "argparse.py", line 1770, in _parse_known_args
  File "argparse.py", line 2027, in _read_args_from_files
UnicodeDecodeError: 'cp932' codec can't decode byte 0xef in position 0: illegal multibyte sequence
[End of Streamlink for Windows with ExitCode 1

this is the error copied from the command line interface.

**Comment by RosadinTV** [comment]
@Dalonomus Can you try using "**Streamlink.bat**" instead of "Streamlink.exe" to see if the same thing happens ?

**Comment by Dalonomus** [comment]
Thank you much appreciated sir ill try this out when I get home

**Comment by RosadinTV** [comment]
@Dalonomus Unicode should be good.
Just in case, I uploaded the file with the encoding already changed (just remove the .txt extension)
[streamlinkrc.txt](https://github.com/streamlink/streamlink-portable/files/1502070/streamlinkrc.txt)

**Comment by Dalonomus** [comment]
Case closed your file worked waaay better than my re-encoded first attempt.  Thank you for the assist.  We can consider this closed i think.  Once again thank you.  Now on to figuring out why normal streamlink won t work for me on this pc :/

**Comment by RosadinTV** [comment]
Awesome, thanks to you for reporting the issue 🍰
It will be fixed by default in the next big update (https://github.com/streamlink/streamlink-portable/projects/1)
