### ISSUE TITLE
version field is corrupt on download and created executable

### ISSUE THREAD

**Issue by Lord-Nightmare** [streamlink/streamlink-portable#23]
Both in the builder/installer, and in the executable once extracted, the version field is corrupt at least if Standalone / Latest Snapshot is chosen.

During run, the messages produced are:
[Streamlink] Extracting program ...
[Streamlink] Program successfully extracted
[Streamlink for Windows vet_versions()['version']
del get_versions
__title__ =  - Git f2f9c75]
[cli][info] Found matching plugin twitch for URL twitch.tv/...

**Comment by Lord-Nightmare** [comment]
I'm curious if commit https://github.com/streamlink/streamlink/commit/416c8347b394c9b1cbaff150450d51a75509dd24 broke it

**Comment by RosadinTV** [comment]
Thanks for the report and details.
I'll fix it soon ❤️

**Comment by RosadinTV** [comment]
@Lord-Nightmare 
This should be fixed now.

**Comment by Lord-Nightmare** [comment]
Confirmed fixed
