### ISSUE TITLE
Portable EXE, Latest Stable Completed with Errors...

### ISSUE THREAD

**Issue by dustycy** [streamlink/streamlink-portable#24]
ERRORS file...

The following dependencies are probably missing:
isodate

Possible solutions:
-Check if a new version is available at https://github.com/streamlink/streamlink-portable
-Manually add the dependencies to 'Files\Resources\Streamlink_Patches.zip' and build again.
-Use an older ZIP archive rather than latest snapshot

VERSION file...

vet_versions()['version'] del get_versions __title__ =  - Git 2dca793

**Comment by RosadinTV** [comment]
Thanks for the report.
isodate error fixed in https://github.com/streamlink/streamlink-portable/commit/2ea0bb649ce44151742cd7dcc83602380cb6f687 (just now)
Version error fixed in https://github.com/streamlink/streamlink-portable/commit/a1699d9706c915ef9139ec30e3597bb47f20055b (21 days ago)
