### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-portable#26]
Streamlink Portable is breaking Streamlink's semantic versioning by applying a custom version format since this commit: a1699d9706c915ef9139ec30e3597bb47f20055b

```
# Streamlink portable
$ ./Streamlink.exe --version
[Streamlink for Windows v0.14.0 - Git 4f5bb1e]
Streamlink.exe 0.14.0@4f5bb1e
[End of Streamlink for Windows with ExitCode 0]

# Regular Streamlink
$ streamlink --version
streamlink 0.14.0+6.g6bf64dda
```

`0.14.0@4f5bb1e` is an invalid versioning format
https://semver.org/

This is breaking the validation of Streamlink in the Streamlink Twitch GUI when the user decides to use Streamlink Portable:
https://github.com/streamlink/streamlink-twitch-gui/issues/581

**Comment by RosadinTV** [comment]
I'll take a look.

**Comment by RosadinTV** [comment]
It should be fixed now (also i added two hotfixes for the last two precompiled releases)

**Comment by bastimeyer** [comment]
Now you have removed the commit id substring from the version string, which is also bad.
bda0e3080aea5f0ebb0d53bed0964b1434947d42

Removing the commit id from dev builds will cause issues when reporting bugs for these versions on the Streamlink issue tracker, as running Streamlink with `-l debug` is mandatory for reporting bugs.

If you had just replaced the `@` sign with a simple `+` (or even with `+g`, as the g indicates that the remaining part is a git commit id substring), then everything would be fine and the version when running `streamlink --version` or `streamlink -l debug` would be a proper semver string, like eg. `0.14.0+0cf6ce0` or `0.14.0+g0cf6ce0`.

**Comment by RosadinTV** [comment]
Everytime you run a command says the version and GIT tag also there is a VERSION.txt file.
I preferred not to try to customize the string again and leave it as plain as possible, I am tired of this kind of errors and the result will not be identical to that produced by Versioneer.

**Comment by RosadinTV** [comment]
Fixed in https://github.com/streamlink/streamlink-portable/commit/1f4ab29fa8d848e990a0707a56c64f052187601b
