### ISSUE TITLE
Not deleting the streamlinkrc.pluginname files that may be inside the Release folder ?

### ISSUE THREAD

**Issue by jalba69** [streamlink/streamlink-portable#27]
Hello RosadinTV,

Will it be possible when using the " Streamlink for Windows (Compiled) " to exclude from deletion any plugin specific file that may be inside the release folder please ?

Some years ago i asked to [not delete the streamlinkrc](https://github.com/streamlink/streamlink/issues/155#issuecomment-262540792) file if it already existed inside the release folder , now i would like to see ( if possible of course ) the same for any of the plugin specific files that may be located there, `streamlinkrc.pluginname` , maybe a wildcard for any _streamlinkrc.*_ files inside the release folder.

(Yes i'm a lazy person and I leave the built streamlink inside the release folder, it's easier and quicker to update it :p )

Thanks a lot :)

**Comment by RosadinTV** [comment]
Hi, thanks for the report.
I 'll fix it when i have some free time.

**Comment by jalba69** [comment]
Thanks ,

and take your time no need to hurry,
Thanks a lot :)

**Comment by RosadinTV** [comment]
Fixed in https://github.com/streamlink/streamlink-portable/commit/1f4ab29fa8d848e990a0707a56c64f052187601b

**Comment by jalba69** [comment]
Thanks a lot for adding this :)
