### ISSUE TITLE
Plugin Request for this

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink-portable#28]
I want to record stream from this site: 

http://m.nexgtv.com/dd-ne.html

**Comment by gravyboat** [comment]
This is the wrong repo for a plugin request, and you also don't have enough details. Create a new issue over in the main Streamlink repo, and make sure to fill out the plugin request template with the appropriate information and if someone wants they will take a look at it. There's also no reason to tag someone 6 hours after you create an issue.
