### ISSUE TITLE
Problems when trying to build with "latest snapshots" option.

### ISSUE THREAD

**Issue by jalba69** [streamlink/streamlink-portable#29]
Hello, 

Using _Streamlink for Windows.exe_ and trying to build Portable or Standalone exe's using "latest snapshot" option gives this when trying to use the built Streamlink : 

> [Streamlink for Windows v0.14.2 - Git 33f677b]
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Temp\\Streamlink Standalone\Streamlink\Streamlink.py", line 9, in <module>
    from streamlink_cli.main import main
  File "C:\Users\Username\AppData\Local\Temp\Streamlink Standalone\Streamlink\streamlink_cli\main.py", line 33, in <module>
    from .argparser import build_parser
  File "C:\Users\Username\AppData\Local\Temp\Streamlink Standalone\Streamlink\streamlink_cli\argparser.py", line 11, in <module>
    from .constants import (
ImportError: cannot import name 'DEFAULT_STREAM_METADATA'
[End of Streamlink for Windows with ExitCode 1]

No problems when building latest Stable version, only when trying the snapshots, not sure what is going on but tried a few times during the last days and different snapshots but always ended up in such errors

Thank you very much.

**Comment by RosadinTV** [comment]
Thanks for the report, fixed ❤️

**Comment by jalba69** [comment]
Thanks a lot for the really quick fix, seems to build correctly the latest snapshot now and the error is gone :) .

However there is a little issue still and i'm not sure if it's on the portable builder end or something else so i post it here and if needed i'll make a new report here or on the main Streamlink page : 

- Following this example here : https://github.com/streamlink/streamlink/issues/1940#issuecomment-406016660 , with the latest snapshot built it returns me this : 
```
[Streamlink for Windows v0.14.2 - Git 6d22855]
usage: Streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --hls-subtitles
[End of Streamlink for Windows with ExitCode 2]
```
Tried a few different command variations but always ending in _--hls-subtitles_ unknown, again i'm not sure of this is a problem coming from the portable builder or else so forgive me for asking.

Thanks a lot for all :)

**Comment by bastimeyer** [comment]
There is no `--hls-subtitles` parameter
https://streamlink.github.io/latest/cli.html#command-line-usage
https://github.com/streamlink/streamlink/blob/master/src/streamlink_cli/argparser.py

**Comment by jalba69** [comment]
Apparently it was added according to the discussion i linked but seems like some files were not merged yet... my bad, forget about this.

Thanks again and sorry for the silly 2nd part
