### ISSUE TITLE
I can't use the camsoda plugin at all. Seems to be the same as this issue https://github.com/streamlink/streamlink/issues/1967

### ISSUE THREAD

**Issue by left1000** [streamlink/streamlink-portable#31]
I can't use the camsoda plugin at all. Seems to be the same as this issue https://github.com/streamlink/streamlink/issues/1967

simply use any url and commands and you will always get exit error code 1 after a json validate not found problem

**Comment by gravyboat** [comment]
Camsoda was removed in this PR: https://github.com/streamlink/streamlink/pull/2003 and we aren't providing support for it, not to mention this is the wrong repo.
