### ISSUE TITLE
Can you download multiple live?

### ISSUE THREAD

**Issue by guilramos** [streamlink/streamlink-portable#35]
Hello, I study in the afternoon and always followed some streams of free fire game on youtube, but many are migrating to the platform bigo tv and some of my favorites broadcast the afternoon and I can no longer follow, because different from youtube bigo tv does not store live, so I would like to know if it is possible to download multiple live on bigo tv using a bat file that runs in the afternoon for example, no problem I leave the computer on in the afternoon, late Weekend I can record live manually by cmd using this code:

streamlink bigo.tv/318717711 best -o "Downloads/%date:~-10,2%-%date:~-7,2%-%date:~-4,4%_%time:~-11,2%-%time:~-8,2%-%time:~-5,2%_NoBruFreeFire.mp4"

so i can record 2 or more live opening each cmd because i have no programmer knowledge and i need your help, so i would like to know if it is possible to create bat file to do multiple live download automatically so i can always check if a stream is open live and capture.
use on windows 10 with

the streams that I follow are
bigo.tv/316936447
bigo.tv/318717711
bigo.tv/319206462
bigo.tv/316301378

if anyone can help me here or by my email: guiramosemail@gmail.com

**Comment by gravyboat** [comment]
This is outside the scope of the project. You'll have to figure this out on your own.
