### ISSUE TITLE
Portable for 1.3.1?

### ISSUE THREAD

**Issue by anephew** [streamlink/streamlink-portable#36]
Portable for 1.3.1? Version 1.3.0 not work with twitch

**Comment by gravyboat** [comment]
There's no one currently maintaining the portable release so I don't know when or if there will be a new release.

**Comment by bastimeyer** [comment]
I'm going to close the issue, as the repo is unmaintained and will be archived.

See the other available installation methods on Windows:
https://streamlink.github.io/latest/install.html#windows
