### ISSUE TITLE
Streamlink-portable doesn't work when launched from a newtork share.

### ISSUE THREAD

**Issue by RobListon** [streamlink/streamlink-portable#4]
I currently use livestreamer on a bunch of computers and have opted to run it from a windows network share to make sure all the clients have the same version. When I copy streamlink-portable to the same share (different directory) it doesn't work.
Just to test where the problem was I copied the streamlink folder to a local drive and it ran just fine.

Here is the command and output from running it from local drive which works:
C:\Temp\streamlink-portable-master\Releases>streamlink --twitch-oauth-token <removed> twitch.tv/summit1g best
[Streamlink for Windows v0.2.0 - Git 045b8fd]
[cli][info] Found matching plugin twitch for URL twitch.tv/summit1g
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as <removed>
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: "C:\Program Files (x86)\K-Lite Codec Pack\MPC-HC64\mpc-hc64.exe"
[cli][info] Player closed
[cli][info] Stream ended
[End of Streamlink for Windows]

And here is the command and output when running it from a network share:
C:\Temp\streamlink-portable-master\Releases>"\\Server\MainShare\streamlink-portable-master\Releases\Streamlink.exe" --twitch-oauth-token <removed> twitch.tv/summit1g best
[Streamlink for Windows]
[End of Streamlink for Windows]

**Comment by RosadinTV** [comment]
@RobListon You are using the Portable or Standalone flavor?
Can you give me the full network shared path of Python.exe (located inside Releases\Python folder) ?

**Comment by RobListon** [comment]
I'm using the portable flavor.
The full path to python is "\\Server\MainShare\streamlink-portable-master\Releases\Python 3.5.2\python.exe"
Also, if I run "Streamlink for Windows.exe" right from a network path I get a .NET error about an unhandled exception: 
************** Exception Text **************
System.ArgumentException: Value of '\\Server\MainShare\streamlink-portable-master\Streamlink for Windows.exe' is not valid for 'filePath'.
   at System.Drawing.Icon.ExtractAssociatedIcon(String filePath, Int32 index)
   at System.Drawing.Icon.ExtractAssociatedIcon(String filePath)
   at Streamlink_for_Windows.Form1.Form1_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by RosadinTV** [comment]
@RobListon It seems the problem here is Windows cannot open the network path in that way, i read in some forums that this type of path must be in this way "\\Server\xxxxxx" .
Just to test try replacing "Files\Resources\PORTABLE_BUILD.vb" with this one (remember to change the extensión to .vb):
[PORTABLE_BUILD.txt](https://github.com/streamlink/streamlink-portable/files/686478/PORTABLE_BUILD.txt)
And then run again the portable builder in a 'real path'
Of course i will release a serious fix for this issue if i can but this is something to test, if you want.

**Comment by RobListon** [comment]
I actually am using the `\\Server\xxxxxx` path format. I just realized that I wasn't using the insert code feature so the double slashes were being stripped in my posts.

**Comment by RobListon** [comment]
Cool. Thanks.

**Comment by RosadinTV** [comment]
@RobListon Done, if you dont want to wait until the PR is approved you can download it here:
https://github.com/RosadinTV/streamlink-portable/archive/master.zip

**Comment by RobListon** [comment]
This version works as expected. Thanks!
