### ISSUE TITLE
Portable upgrade : compat.py not updated on install

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink-portable#7]
I updated portable streamlink to 0.3.0. While checking in command prompt, I noticed it didn't update library compat.py which is located in `streamlink-portable-master\Streamlink for Windows (Compiled)\Releases\Streamlink\streamlink`

compat.py is dated from 12 October 2016, but it has been updated on 23 January 2017. 
Take a look in Command Prompt output. 

```
streamlink-portable-master\streamlink-portable-master\Streamlink for Windows (Compiled)\Releases>streamlink
[Streamlink for Windows v0.3.0 - Git 5b9f68a]
Failed to load plugin srgssr:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Ddr\Downloads\streamlink-portable-master\streamlink-portable-ma
ster\Streamlink for Windows (Compiled)\Releases\Streamlink\streamlink\plugins\sr
gssr.py", line 6, in <module>
    from streamlink.compat import urlparse, parse_qsl, urlencode, urlunparse
ImportError: cannot import name 'urlencode'

usage: Streamlink.exe [OPTIONS] <URL> [STREAM]

```

**Comment by RosadinTV** [comment]
Hi, the problem here is that i freeze Compat.py to prevent errors when new libraries are added, but as you said the file was updated adding a new import needed for a plugin.
I'm on vacations and i dont have a PC here to update the Compat.py located inside "Files/Resources/Streamlink_Patches.zip" so if anyone can submit a PR would be good.

**Comment by karlo2105** [comment]
I pulled request with Compat.py updated within folder Streamlink_Patches.zip

**Comment by RosadinTV** [comment]
Fixed in https://github.com/streamlink/streamlink-portable/pull/11
